/* BEGIN Annadir columnas Facturada, ID_Cita, ID_LineaFactura */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
COMMIT
BEGIN TRANSACTION
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LCOMPARATIVAS_TRATAMIENTOS ADD
	Facturada bit NULL,
	ID_Cita int NULL,
	ID_LineaFactura int NULL
GO
ALTER TABLE dbo.LCOMPARATIVAS_TRATAMIENTOS ADD CONSTRAINT
	DF_LCOMPARATIVAS_TRATAMIENTOS_Facturada DEFAULT 0 FOR Facturada
GO
ALTER TABLE dbo.LCOMPARATIVAS_TRATAMIENTOS ADD CONSTRAINT
	FK_LCOMPARATIVAS_TRATAMIENTOS_CITAS FOREIGN KEY
	(
	ID_Cita
	) REFERENCES dbo.CITAS
	(
	IDCITA
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.LCOMPARATIVAS_TRATAMIENTOS ADD CONSTRAINT
	FK_LCOMPARATIVAS_TRATAMIENTOS_LINEASFACTURAS FOREIGN KEY
	(
	ID_LineaFactura
	) REFERENCES dbo.LINEASFACTURAS
	(
	IDLINEAFACTURA
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO
COMMIT

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LCOMPARATIVAS_TRATAMIENTOS ADD
	ID_LineaCita bigint NULL
GO
COMMIT
GO
UPDATE [LCOMPARATIVAS_TRATAMIENTOS] SET [Facturada] = 0 WHERE Facturada is null;
GO

/* Annadir campo RefLineaTratamiento a tabla LineasCita.*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
go
BEGIN TRANSACTION
Go
ALTER TABLE dbo.LineasCitas ADD
	RefLineaTratamiento int NULL
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	FK_LineasCitas_LCOMPARATIVAS_TRATAMIENTOS FOREIGN KEY
	(
	RefLineaTratamiento
	) REFERENCES dbo.LCOMPARATIVAS_TRATAMIENTOS
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT

Update VariablesGlobales Set Valor = '1.0.1.8' where Clave = 'DB_Version';