/* BEGIN Aññadir campo DescuentoPercent a las LineasCitas.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas ADD
	DescuentoPercent float(53) NULL
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	DF_LineasCitas_DescuentoPercent DEFAULT 0 FOR DescuentoPercent
GO
COMMIT

/*END Aññadir campo DescuentoPercent a las LineasCitas.*/

/* BEGIN Modificar Tabla d_Presupuestos para aññadir DescuentoPercent */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.d_PresupuestoLineas ADD
	DescuentoPercent float(53) NULL
GO
ALTER TABLE dbo.d_PresupuestoLineas ADD CONSTRAINT
	DF_d_PresupuestoLineas_DescuentoPercent DEFAULT 0 FOR DescuentoPercent
GO
COMMIT

/*END Modificar Tabla d_Presupuestos para aññadir DescuentoPercent y campo Notas*/

/*BEGIN Annadir columna descuento tabla CITAS */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS ADD
	Descuento float(53) NULL
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	DF_CITAS_Descuento DEFAULT 0 FOR Descuento
GO
COMMIT
/*END Annadir columna descuento tabla CITAS */


/* BEGIN Annadir columna Descuento a LINEASFACTURAS*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS ADD
	Descuento float(53) NULL
GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	DF_LINEASFACTURAS_Descuento DEFAULT 0 FOR Descuento
GO
COMMIT
/*END Annadir columna Descuento a LINEASFACTURAS*/


/* BEGIN Annadir columna Descuento a Facturas */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FACTURAS ADD
	Descuento float(53) NULL
GO
ALTER TABLE dbo.FACTURAS ADD CONSTRAINT
	DF_FACTURAS_Descuento DEFAULT 0 FOR Descuento
GO
COMMIT
/* END Annadir columna Descuento a Facturas*/

/* BEGIN Annadir ImporteOriginal a LineasFacturas.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS ADD
	ImporteOriginal float(53) NULL
GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	DF_LINEASFACTURAS_ImporteOriginal DEFAULT 0 FOR ImporteOriginal
GO
COMMIT
/*END Annadir ImporteOriginal a LineasFacturas*/


UPDATE FICHEROS SET IDSECCION = 9 WHERE IDSECCION IS NULL;


UPDATE LineasCitas SET DescuentoPercent = 0 WHERE DescuentoPercent is null
UPDATE LINEASFACTURAS SET Descuento = 0 WHERE Descuento is null

Update VariablesGlobales Set Valor = '1.0.1.2' where Clave = 'DB_Version';
