
/* BEGIN Modificacion de campo TLFONO en PACIENTES para que tenga longitud 20 */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__PAGOB__4E88ABD4
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__DEFUN__4F7CD00D
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__SOCIO__5165187F
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__ACTIV__52593CB8
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_WEB
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_EMAIL
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_CODIGOPROPIO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_BENEFICIARIOCODIGOSOCIO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_BENEFICIARIOPARENTESCO
GO
CREATE TABLE dbo.Tmp_PACIENTES
	(
	NOMBRE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	APELLIDO1 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	APELLIDO2 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DOMICILIO varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TLFNO nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MOVIL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROFESION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOCALIDAD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CP varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFEMPRESA int NULL,
	DNI varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHAN datetime NULL,
	OBSERVACIONES varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROVINCIA varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NSS varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUESTO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REGIMEN varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TARJETASANITARIA varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFMUTUA int NULL,
	CPACIENTE int NOT NULL,
	SEXO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHAALTA datetime NULL,
	TUTOR varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAGOBANCO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ENTIDAD varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OFICINA varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DC varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TITULAR varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUENTA varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEFUNCION varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NIE varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PASAPORTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFPAIS int NOT NULL,
	FOTO image NULL,
	FOTOGRAFIA varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOCIO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACTIVO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFFORMAPAGO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHABAJA datetime NULL,
	CONOCIO varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEB varchar(250) NOT NULL,
	EMAIL varchar(250) NOT NULL,
	CODIGOPROPIO varchar(50) NOT NULL,
	BENEFICIARIOCODIGOSOCIO int NOT NULL,
	BENEFICIARIOPARENTESCO varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__PAGOB__4E88ABD4 DEFAULT ('N') FOR PAGOBANCO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__DEFUN__4F7CD00D DEFAULT ('N') FOR DEFUNCION
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__SOCIO__5165187F DEFAULT ('N') FOR SOCIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__ACTIV__52593CB8 DEFAULT ('S') FOR ACTIVO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_WEB DEFAULT ('') FOR WEB
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_EMAIL DEFAULT ('') FOR EMAIL
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_CODIGOPROPIO DEFAULT ('') FOR CODIGOPROPIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_BENEFICIARIOCODIGOSOCIO DEFAULT ('') FOR BENEFICIARIOCODIGOSOCIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_BENEFICIARIOPARENTESCO DEFAULT ('') FOR BENEFICIARIOPARENTESCO
GO
IF EXISTS(SELECT * FROM dbo.PACIENTES)
	 EXEC('INSERT INTO dbo.Tmp_PACIENTES (NOMBRE, APELLIDO1, APELLIDO2, DOMICILIO, TLFNO, MOVIL, PROFESION, LOCALIDAD, CP, REFEMPRESA, DNI, FECHAN, OBSERVACIONES, PROVINCIA, NSS, PUESTO, REGIMEN, TARJETASANITARIA, REFMUTUA, CPACIENTE, SEXO, FECHAALTA, TUTOR, PAGOBANCO, ENTIDAD, OFICINA, DC, TITULAR, CUENTA, DEFUNCION, NIE, PASAPORTE, REFPAIS, FOTO, FOTOGRAFIA, SOCIO, ACTIVO, REFFORMAPAGO, FECHABAJA, CONOCIO, WEB, EMAIL, CODIGOPROPIO, BENEFICIARIOCODIGOSOCIO, BENEFICIARIOPARENTESCO)
		SELECT NOMBRE, APELLIDO1, APELLIDO2, DOMICILIO, CONVERT(nvarchar(20), TLFNO), MOVIL, PROFESION, LOCALIDAD, CP, REFEMPRESA, DNI, FECHAN, OBSERVACIONES, PROVINCIA, NSS, PUESTO, REGIMEN, TARJETASANITARIA, REFMUTUA, CPACIENTE, SEXO, FECHAALTA, TUTOR, PAGOBANCO, ENTIDAD, OFICINA, DC, TITULAR, CUENTA, DEFUNCION, NIE, PASAPORTE, REFPAIS, FOTO, FOTOGRAFIA, SOCIO, ACTIVO, REFFORMAPAGO, FECHABAJA, CONOCIO, WEB, EMAIL, CODIGOPROPIO, BENEFICIARIOCODIGOSOCIO, BENEFICIARIOPARENTESCO FROM dbo.PACIENTES WITH (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.Asociados
	DROP CONSTRAINT FK_Asociados_PACIENTES
GO
ALTER TABLE dbo.Asociados
	DROP CONSTRAINT FK_Asociados_PACIENTES1
GO
ALTER TABLE dbo.ANALITICAS
	DROP CONSTRAINT fk_analiticapaciente
GO
ALTER TABLE dbo.AUDIOMETRIAS
	DROP CONSTRAINT fk_audiometrias
GO
ALTER TABLE dbo.COMPARATIVAS
	DROP CONSTRAINT fk_comparativaspaciente
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT FK_N_Ticket_N_Pacientes
GO
ALTER TABLE dbo.DERIVACIONES
	DROP CONSTRAINT fk_derivacionespaciente
GO
ALTER TABLE dbo.FACTURAS
	DROP CONSTRAINT fkfacturaspaciente
GO
ALTER TABLE dbo.FICHEROS
	DROP CONSTRAINT fk_ficheros
GO
ALTER TABLE dbo.HISTORIALES
	DROP CONSTRAINT fkhistorialespaciente
GO
ALTER TABLE dbo.IMAGENES
	DROP CONSTRAINT fkimagenespaciente
GO
ALTER TABLE dbo.INFORMACIONPRIMARIA
	DROP CONSTRAINT fk_informacionprimariapaciente
GO
ALTER TABLE dbo.LEMPRESAS
	DROP CONSTRAINT fk_lempresaspacientes
GO
ALTER TABLE dbo.LINEASALARMA
	DROP CONSTRAINT fklineasalarmapaciente
GO
ALTER TABLE dbo.N_Factura
	DROP CONSTRAINT FK_N_Factura_N_Pacientes
GO
ALTER TABLE dbo.LMUTUAS
	DROP CONSTRAINT fk_lmutuas_pacientes
GO
ALTER TABLE dbo.PRESUPUESTOS
	DROP CONSTRAINT fkpresupuestopaciente
GO
ALTER TABLE dbo.RECETAS
	DROP CONSTRAINT fkrecetaspaciente
GO
ALTER TABLE dbo.RECIBOS
	DROP CONSTRAINT FK_RECIBOS_PACIENTES
GO
ALTER TABLE dbo.N_Procesos
	DROP CONSTRAINT FK_N_Procesos_PACIENTES
GO
ALTER TABLE dbo.N_Partes_Asistencia
	DROP CONSTRAINT FK_N_Partes_Asistencia_PACIENTES
GO
ALTER TABLE dbo.AntecedentesDiagnosticos
	DROP CONSTRAINT FK_AntecedentesDiagnosticos_PACIENTES
GO
DROP TABLE dbo.PACIENTES
GO
EXECUTE sp_rename N'dbo.Tmp_PACIENTES', N'PACIENTES', 'OBJECT' 
GO
ALTER TABLE dbo.PACIENTES ADD CONSTRAINT
	PK_PACIENTES PRIMARY KEY CLUSTERED 
	(
	CPACIENTE
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AntecedentesDiagnosticos ADD CONSTRAINT
	FK_AntecedentesDiagnosticos_PACIENTES FOREIGN KEY
	(
	CPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Partes_Asistencia ADD CONSTRAINT
	FK_N_Partes_Asistencia_PACIENTES FOREIGN KEY
	(
	ID_Paciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Procesos ADD CONSTRAINT
	FK_N_Procesos_PACIENTES FOREIGN KEY
	(
	ID_Paciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RECIBOS ADD CONSTRAINT
	FK_RECIBOS_PACIENTES FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RECETAS ADD CONSTRAINT
	fkrecetaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PRESUPUESTOS ADD CONSTRAINT
	fkpresupuestopaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LMUTUAS ADD CONSTRAINT
	fk_lmutuas_pacientes FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Factura ADD CONSTRAINT
	FK_N_Factura_N_Pacientes FOREIGN KEY
	(
	ID_Cliente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASALARMA ADD CONSTRAINT
	fklineasalarmapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LEMPRESAS ADD CONSTRAINT
	fk_lempresaspacientes FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INFORMACIONPRIMARIA ADD CONSTRAINT
	fk_informacionprimariapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.IMAGENES ADD CONSTRAINT
	fkimagenespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.HISTORIALES ADD CONSTRAINT
	fkhistorialespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FICHEROS ADD CONSTRAINT
	fk_ficheros FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FACTURAS ADD CONSTRAINT
	fkfacturaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DERIVACIONES ADD CONSTRAINT
	fk_derivacionespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	FK_N_Ticket_N_Pacientes FOREIGN KEY
	(
	ID_Cliente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.COMPARATIVAS ADD CONSTRAINT
	fk_comparativaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AUDIOMETRIAS ADD CONSTRAINT
	fk_audiometrias FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ANALITICAS ADD CONSTRAINT
	fk_analiticapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Asociados ADD CONSTRAINT
	FK_Asociados_PACIENTES FOREIGN KEY
	(
	IDPacienteBeneficiario
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.Asociados ADD CONSTRAINT
	FK_Asociados_PACIENTES1 FOREIGN KEY
	(
	IDPacienteOrigen
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT

/* END Modificacion de campo TLFONO en PACIENTES para que tenga longitud 20 */ 


/* BEGIN Annadir campo int Favorito a tabla N_Articulos */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Articulos ADD
	Favorito int NULL
GO
COMMIT
/* END Annadir campo int Favorito a tabla N_Articulos */




/*BEGIN EN TPV/Tickets, modificar la tabla N_Tickets para que la Fecha Pago permita nulls */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT FK_N_Ticket_N_Pacientes
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT FK_N_Ticket_N_Ticket_Tipos
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT FK_N_Ticket_FormasPago
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT DF_Ticket_Fecha
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT DF_N_Ticket_REPorciento
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT DF_N_Ticket_ReCantidad
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT DF_N_Ticket_PortePagado
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT DF_N_Ticket_PorteDebido
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT DF_N_Ticket_Pagado
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT DF_N_Ticket_FechaPagado
GO
CREATE TABLE dbo.Tmp_N_Ticket
	(
	ID_Ticket bigint NOT NULL IDENTITY (1, 1),
	Codigo nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ID_TipoTicket int NULL,
	Referencia nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Fecha datetime NOT NULL,
	ID_Estado int NULL,
	ID_Cliente int NULL,
	ID_FormaPago varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IRPFPorciento float(53) NULL,
	IRPFCantidad float(53) NULL,
	Total float(53) NULL,
	Observaciones nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PlazoEntrega datetime NULL,
	Validez nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PortePagado bit NULL,
	PorteDebido bit NULL,
	PorteTexto nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Privado nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DocumentacionAsociada nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Comentarios nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Imagen image NULL,
	Pagado bit NOT NULL,
	FechaPagado datetime NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_N_Ticket ADD CONSTRAINT
	DF_Ticket_Fecha DEFAULT (getdate()) FOR Fecha
GO
ALTER TABLE dbo.Tmp_N_Ticket ADD CONSTRAINT
	DF_N_Ticket_REPorciento DEFAULT ((0)) FOR IRPFPorciento
GO
ALTER TABLE dbo.Tmp_N_Ticket ADD CONSTRAINT
	DF_N_Ticket_ReCantidad DEFAULT ((0)) FOR IRPFCantidad
GO
ALTER TABLE dbo.Tmp_N_Ticket ADD CONSTRAINT
	DF_N_Ticket_PortePagado DEFAULT ((1)) FOR PortePagado
GO
ALTER TABLE dbo.Tmp_N_Ticket ADD CONSTRAINT
	DF_N_Ticket_PorteDebido DEFAULT ((0)) FOR PorteDebido
GO
ALTER TABLE dbo.Tmp_N_Ticket ADD CONSTRAINT
	DF_N_Ticket_Pagado DEFAULT ((0)) FOR Pagado
GO
ALTER TABLE dbo.Tmp_N_Ticket ADD CONSTRAINT
	DF_N_Ticket_FechaPagado DEFAULT (getdate()) FOR FechaPagado
GO
SET IDENTITY_INSERT dbo.Tmp_N_Ticket ON
GO
IF EXISTS(SELECT * FROM dbo.N_Ticket)
	 EXEC('INSERT INTO dbo.Tmp_N_Ticket (ID_Ticket, Codigo, ID_TipoTicket, Referencia, Fecha, ID_Estado, ID_Cliente, ID_FormaPago, IRPFPorciento, IRPFCantidad, Total, Observaciones, PlazoEntrega, Validez, PortePagado, PorteDebido, PorteTexto, Privado, DocumentacionAsociada, Comentarios, Imagen, Pagado, FechaPagado)
		SELECT ID_Ticket, Codigo, ID_TipoTicket, Referencia, Fecha, ID_Estado, ID_Cliente, ID_FormaPago, IRPFPorciento, IRPFCantidad, Total, Observaciones, PlazoEntrega, Validez, PortePagado, PorteDebido, PorteTexto, Privado, DocumentacionAsociada, Comentarios, Imagen, Pagado, FechaPagado FROM dbo.N_Ticket WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_N_Ticket OFF
GO
ALTER TABLE dbo.N_Ticket_Lineas
	DROP CONSTRAINT FK_N_Ticket_Lineas_N_Ticket
GO
ALTER TABLE dbo.N_Ticket_Totales
	DROP CONSTRAINT FK_N_Ticket_Totales_N_Ticket
GO
DROP TABLE dbo.N_Ticket
GO
EXECUTE sp_rename N'dbo.Tmp_N_Ticket', N'N_Ticket', 'OBJECT' 
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	PK_N_Ticket PRIMARY KEY CLUSTERED 
	(
	ID_Ticket
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	FK_N_Ticket_FormasPago FOREIGN KEY
	(
	ID_FormaPago
	) REFERENCES dbo.FORMASPAGO
	(
	CODIGO
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	FK_N_Ticket_N_Ticket_Tipos FOREIGN KEY
	(
	ID_TipoTicket
	) REFERENCES dbo.N_Ticket_Tipos
	(
	ID_TipoTicket
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	FK_N_Ticket_N_Pacientes FOREIGN KEY
	(
	ID_Cliente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket_Totales ADD CONSTRAINT
	FK_N_Ticket_Totales_N_Ticket FOREIGN KEY
	(
	ID_Ticket
	) REFERENCES dbo.N_Ticket
	(
	ID_Ticket
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket_Lineas ADD CONSTRAINT
	FK_N_Ticket_Lineas_N_Ticket FOREIGN KEY
	(
	ID_Ticket
	) REFERENCES dbo.N_Ticket
	(
	ID_Ticket
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT

/*END EN TPV/Tickets, modificar la tabla N_Tickets para que la Fecha Pago permita nulls */

/* BEGIN Creacion de la Tabla EntregasCuenta */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EntregasCuenta](
	[IDEntregaCuenta] [bigint] IDENTITY(1,1) NOT NULL,
	[IDPaciente] [int] NULL,
	[Fecha] [datetime] NULL CONSTRAINT [DF_EntregasCuenta_Fecha]  DEFAULT (getdate()),
	[TipoDocumento] [int] NULL,
	[CodDocumento] [nvarchar](50) NULL,
	[Descripcion] [nvarchar](50) NULL,
	[Importe] [float] NULL CONSTRAINT [DF_EntregasCuenta_Importe]  DEFAULT ((0)),
	[IDUsuarioEfectua] [int] NULL,
 CONSTRAINT [PK_EntregasCuenta] PRIMARY KEY CLUSTERED 
(
	[IDEntregaCuenta] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[EntregasCuenta]  WITH CHECK ADD  CONSTRAINT [FK_EntregasCuenta_PACIENTES] FOREIGN KEY([IDPaciente])
REFERENCES [dbo].[PACIENTES] ([CPACIENTE])
GO
ALTER TABLE [dbo].[EntregasCuenta] CHECK CONSTRAINT [FK_EntregasCuenta_PACIENTES]
GO
ALTER TABLE [dbo].[EntregasCuenta]  WITH CHECK ADD  CONSTRAINT [FK_EntregasCuenta_USUARIOS] FOREIGN KEY([IDUsuarioEfectua])
REFERENCES [dbo].[USUARIOS] ([CODIGO])
GO
ALTER TABLE [dbo].[EntregasCuenta] CHECK CONSTRAINT [FK_EntregasCuenta_USUARIOS]
GO
/* END Creacion de la Tabla EntregasCuenta */

/* BEGIN Creacion de la Tabla PagosPaciente */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PagosPaciente](
	[IDEntrega] [bigint] IDENTITY(1,1) NOT NULL,
	[IDPaciente] [int] NULL,
	[Fecha] [datetime] NULL CONSTRAINT [DF_PagosCliente_Fecha]  DEFAULT (getdate()),
	[Importe] [float] NULL,
	[IDFormaPago] [varchar](10) NULL,
	[Notas] [nvarchar](200) NULL,
	[IDUsuario] [int] NULL,
 CONSTRAINT [PK_PagosCliente] PRIMARY KEY CLUSTERED 
(
	[IDEntrega] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[PagosPaciente]  WITH CHECK ADD  CONSTRAINT [FK_PagosCliente_PACIENTES] FOREIGN KEY([IDPaciente])
REFERENCES [dbo].[PACIENTES] ([CPACIENTE])
GO
ALTER TABLE [dbo].[PagosPaciente] CHECK CONSTRAINT [FK_PagosCliente_PACIENTES]
GO
ALTER TABLE [dbo].[PagosPaciente]  WITH CHECK ADD  CONSTRAINT [FK_PagosCliente_USUARIOS] FOREIGN KEY([IDUsuario])
REFERENCES [dbo].[USUARIOS] ([CODIGO])
GO
ALTER TABLE [dbo].[PagosPaciente] CHECK CONSTRAINT [FK_PagosCliente_USUARIOS]
/* END Creacion de la Tabla PagosPaciente */

/* BEGIN Modificacion de Tabla MUTUAS para incluir NoContrato */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.MUTUAS ADD
	NoContrato nvarchar(50) NULL
GO
COMMIT
/* END Modificacion de Tabla MUTUAS para incluir NoContrato */


/*BEGIN Creacion Tabla ReportesPersonalizados*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReportesPersonalizados](
	[IDReporte] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](100) NULL,
	[ID_Gabinete] [int] NULL CONSTRAINT [DF_ReportesPersonalizados_ID_Gabinete]  DEFAULT ((1)),
	[Seccion] [int] NULL CONSTRAINT [DF_Table1_ID_Seccion]  DEFAULT ((1)),
	[FileName] [nvarchar](100) NULL,
	[FechaAnnadido] [datetime] NULL CONSTRAINT [DF_ReportesPersonalizados_FechaAnnadido]  DEFAULT (getdate()),
	[DataSourceName] [nvarchar](100) NULL,
	[PorDefecto] [bit] NULL CONSTRAINT [DF_ReportesPersonalizados_PorDefecto]  DEFAULT ((0)),
 CONSTRAINT [PK_ReportesPersonalizados] PRIMARY KEY CLUSTERED 
(
	[IDReporte] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

/*END ReportesPersonalizados*/



/*BEGIN Modificacion del campo Movil de paciente para que sea nvarchar(20) */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__PAGOB__4E88ABD4
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__DEFUN__4F7CD00D
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__SOCIO__5165187F
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__ACTIV__52593CB8
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_WEB
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_EMAIL
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_CODIGOPROPIO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_BENEFICIARIOCODIGOSOCIO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_BENEFICIARIOPARENTESCO
GO
CREATE TABLE dbo.Tmp_PACIENTES
	(
	NOMBRE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	APELLIDO1 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	APELLIDO2 varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DOMICILIO varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TLFNO nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MOVIL nvarchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROFESION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOCALIDAD varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CP varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFEMPRESA int NULL,
	DNI varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHAN datetime NULL,
	OBSERVACIONES varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROVINCIA varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NSS varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUESTO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REGIMEN varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TARJETASANITARIA varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFMUTUA int NULL,
	CPACIENTE int NOT NULL,
	SEXO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHAALTA datetime NULL,
	TUTOR varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAGOBANCO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ENTIDAD varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OFICINA varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DC varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TITULAR varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUENTA varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEFUNCION varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NIE varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PASAPORTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFPAIS int NOT NULL,
	FOTO image NULL,
	FOTOGRAFIA varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOCIO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACTIVO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFFORMAPAGO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHABAJA datetime NULL,
	CONOCIO varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEB varchar(250) NOT NULL,
	EMAIL varchar(250) NOT NULL,
	CODIGOPROPIO varchar(50) NOT NULL,
	BENEFICIARIOCODIGOSOCIO int NOT NULL,
	BENEFICIARIOPARENTESCO varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__PAGOB__4E88ABD4 DEFAULT ('N') FOR PAGOBANCO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__DEFUN__4F7CD00D DEFAULT ('N') FOR DEFUNCION
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__SOCIO__5165187F DEFAULT ('N') FOR SOCIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__ACTIV__52593CB8 DEFAULT ('S') FOR ACTIVO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_WEB DEFAULT ('') FOR WEB
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_EMAIL DEFAULT ('') FOR EMAIL
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_CODIGOPROPIO DEFAULT ('') FOR CODIGOPROPIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_BENEFICIARIOCODIGOSOCIO DEFAULT ('') FOR BENEFICIARIOCODIGOSOCIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_BENEFICIARIOPARENTESCO DEFAULT ('') FOR BENEFICIARIOPARENTESCO
GO
IF EXISTS(SELECT * FROM dbo.PACIENTES)
	 EXEC('INSERT INTO dbo.Tmp_PACIENTES (NOMBRE, APELLIDO1, APELLIDO2, DOMICILIO, TLFNO, MOVIL, PROFESION, LOCALIDAD, CP, REFEMPRESA, DNI, FECHAN, OBSERVACIONES, PROVINCIA, NSS, PUESTO, REGIMEN, TARJETASANITARIA, REFMUTUA, CPACIENTE, SEXO, FECHAALTA, TUTOR, PAGOBANCO, ENTIDAD, OFICINA, DC, TITULAR, CUENTA, DEFUNCION, NIE, PASAPORTE, REFPAIS, FOTO, FOTOGRAFIA, SOCIO, ACTIVO, REFFORMAPAGO, FECHABAJA, CONOCIO, WEB, EMAIL, CODIGOPROPIO, BENEFICIARIOCODIGOSOCIO, BENEFICIARIOPARENTESCO)
		SELECT NOMBRE, APELLIDO1, APELLIDO2, DOMICILIO, TLFNO, CONVERT(nvarchar(20), MOVIL), PROFESION, LOCALIDAD, CP, REFEMPRESA, DNI, FECHAN, OBSERVACIONES, PROVINCIA, NSS, PUESTO, REGIMEN, TARJETASANITARIA, REFMUTUA, CPACIENTE, SEXO, FECHAALTA, TUTOR, PAGOBANCO, ENTIDAD, OFICINA, DC, TITULAR, CUENTA, DEFUNCION, NIE, PASAPORTE, REFPAIS, FOTO, FOTOGRAFIA, SOCIO, ACTIVO, REFFORMAPAGO, FECHABAJA, CONOCIO, WEB, EMAIL, CODIGOPROPIO, BENEFICIARIOCODIGOSOCIO, BENEFICIARIOPARENTESCO FROM dbo.PACIENTES WITH (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.PagosPaciente
	DROP CONSTRAINT FK_PagosCliente_PACIENTES
GO
ALTER TABLE dbo.AntecedentesDiagnosticos
	DROP CONSTRAINT FK_AntecedentesDiagnosticos_PACIENTES
GO
ALTER TABLE dbo.N_Partes_Asistencia
	DROP CONSTRAINT FK_N_Partes_Asistencia_PACIENTES
GO
ALTER TABLE dbo.N_Procesos
	DROP CONSTRAINT FK_N_Procesos_PACIENTES
GO
ALTER TABLE dbo.RECIBOS
	DROP CONSTRAINT FK_RECIBOS_PACIENTES
GO
ALTER TABLE dbo.EntregasCuenta
	DROP CONSTRAINT FK_EntregasCuenta_PACIENTES
GO
ALTER TABLE dbo.RECETAS
	DROP CONSTRAINT fkrecetaspaciente
GO
ALTER TABLE dbo.PRESUPUESTOS
	DROP CONSTRAINT fkpresupuestopaciente
GO
ALTER TABLE dbo.LMUTUAS
	DROP CONSTRAINT fk_lmutuas_pacientes
GO
ALTER TABLE dbo.N_Factura
	DROP CONSTRAINT FK_N_Factura_N_Pacientes
GO
ALTER TABLE dbo.LINEASALARMA
	DROP CONSTRAINT fklineasalarmapaciente
GO
ALTER TABLE dbo.LEMPRESAS
	DROP CONSTRAINT fk_lempresaspacientes
GO
ALTER TABLE dbo.INFORMACIONPRIMARIA
	DROP CONSTRAINT fk_informacionprimariapaciente
GO
ALTER TABLE dbo.IMAGENES
	DROP CONSTRAINT fkimagenespaciente
GO
ALTER TABLE dbo.HISTORIALES
	DROP CONSTRAINT fkhistorialespaciente
GO
ALTER TABLE dbo.FICHEROS
	DROP CONSTRAINT fk_ficheros
GO
ALTER TABLE dbo.FACTURAS
	DROP CONSTRAINT fkfacturaspaciente
GO
ALTER TABLE dbo.DERIVACIONES
	DROP CONSTRAINT fk_derivacionespaciente
GO
ALTER TABLE dbo.COMPARATIVAS
	DROP CONSTRAINT fk_comparativaspaciente
GO
ALTER TABLE dbo.AUDIOMETRIAS
	DROP CONSTRAINT fk_audiometrias
GO
ALTER TABLE dbo.ANALITICAS
	DROP CONSTRAINT fk_analiticapaciente
GO
ALTER TABLE dbo.Asociados
	DROP CONSTRAINT FK_Asociados_PACIENTES
GO
ALTER TABLE dbo.Asociados
	DROP CONSTRAINT FK_Asociados_PACIENTES1
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT FK_N_Ticket_N_Pacientes
GO

DROP TABLE dbo.PACIENTES
GO
EXECUTE sp_rename N'dbo.Tmp_PACIENTES', N'PACIENTES', 'OBJECT' 
GO
ALTER TABLE dbo.PACIENTES ADD CONSTRAINT
	PK_PACIENTES PRIMARY KEY CLUSTERED 
	(
	CPACIENTE
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT

BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	FK_N_Ticket_N_Pacientes FOREIGN KEY
	(
	ID_Cliente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Asociados ADD CONSTRAINT
	FK_Asociados_PACIENTES FOREIGN KEY
	(
	IDPacienteBeneficiario
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.Asociados ADD CONSTRAINT
	FK_Asociados_PACIENTES1 FOREIGN KEY
	(
	IDPacienteOrigen
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ANALITICAS ADD CONSTRAINT
	fk_analiticapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AUDIOMETRIAS ADD CONSTRAINT
	fk_audiometrias FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.COMPARATIVAS ADD CONSTRAINT
	fk_comparativaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DERIVACIONES ADD CONSTRAINT
	fk_derivacionespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FACTURAS ADD CONSTRAINT
	fkfacturaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FICHEROS ADD CONSTRAINT
	fk_ficheros FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.HISTORIALES ADD CONSTRAINT
	fkhistorialespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.IMAGENES ADD CONSTRAINT
	fkimagenespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INFORMACIONPRIMARIA ADD CONSTRAINT
	fk_informacionprimariapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LEMPRESAS ADD CONSTRAINT
	fk_lempresaspacientes FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASALARMA ADD CONSTRAINT
	fklineasalarmapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Factura ADD CONSTRAINT
	FK_N_Factura_N_Pacientes FOREIGN KEY
	(
	ID_Cliente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LMUTUAS ADD CONSTRAINT
	fk_lmutuas_pacientes FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PRESUPUESTOS ADD CONSTRAINT
	fkpresupuestopaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RECETAS ADD CONSTRAINT
	fkrecetaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.EntregasCuenta ADD CONSTRAINT
	FK_EntregasCuenta_PACIENTES FOREIGN KEY
	(
	IDPaciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RECIBOS ADD CONSTRAINT
	FK_RECIBOS_PACIENTES FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Procesos ADD CONSTRAINT
	FK_N_Procesos_PACIENTES FOREIGN KEY
	(
	ID_Paciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Partes_Asistencia ADD CONSTRAINT
	FK_N_Partes_Asistencia_PACIENTES FOREIGN KEY
	(
	ID_Paciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AntecedentesDiagnosticos ADD CONSTRAINT
	FK_AntecedentesDiagnosticos_PACIENTES FOREIGN KEY
	(
	CPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PagosPaciente ADD CONSTRAINT
	FK_PagosCliente_PACIENTES FOREIGN KEY
	(
	IDPaciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
/*END Modificacion del campo Movil de paciente para que sea nvarchar(20)*/
Update VariablesGlobales Set Valor = '1.0.0.9' where Clave = 'DB_Version';