print 'añadimos fk a ConceptosFacturable - paciente';
GO
ALTER TABLE dbo.CONCEPTOSFACTURABLES WITH NOCHECK ADD CONSTRAINT
	FK_CONCEPTOSFACTURABLES_PACIENTES FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO

PRINT 'Añadimos fk a Citas - paciente';
GO
ALTER TABLE dbo.CITAS WITH NOCHECK ADD CONSTRAINT
	FK_CITAS_PACIENTES FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO

Print 'Inserto el permiso para Migrar Pacientes';
GO
INSERT INTO ROLESITEMS VALUES (104,'Migrar Paciente')
GO
INSERT INTO ROLESITEMS VALUES (0,'Inicio Sistema')
GO

Print 'Cambiamos el tamaño del campo DVARCHAR';
GO
/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DATOSCOMPARATIVA
	DROP CONSTRAINT fk_datoscomparativalcomparativa
GO
ALTER TABLE dbo.LCOMPARATIVAS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DATOSCOMPARATIVA
	DROP CONSTRAINT fk_datoscomparativamodelodato
GO
ALTER TABLE dbo.MODELOSDATOS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_DATOSCOMPARATIVA
	(
	ID int NOT NULL IDENTITY (1, 1) NOT FOR REPLICATION,
	REFLCOMPARATIVA int NULL,
	DFLOAT real NULL,
	DBOOLEAN varchar(1) NULL,
	DVARCHAR varchar(1000) NULL,
	REFMODELODATO int NULL,
	DXML xml NULL,
	OcultarImpresionCliente bit NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_DATOSCOMPARATIVA SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_DATOSCOMPARATIVA ON
GO
IF EXISTS(SELECT * FROM dbo.DATOSCOMPARATIVA)
	 EXEC('INSERT INTO dbo.Tmp_DATOSCOMPARATIVA (ID, REFLCOMPARATIVA, DFLOAT, DBOOLEAN, DVARCHAR, REFMODELODATO, DXML, OcultarImpresionCliente)
		SELECT ID, REFLCOMPARATIVA, DFLOAT, DBOOLEAN, DVARCHAR, REFMODELODATO, DXML, OcultarImpresionCliente FROM dbo.DATOSCOMPARATIVA WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_DATOSCOMPARATIVA OFF
GO
DROP TABLE dbo.DATOSCOMPARATIVA
GO
EXECUTE sp_rename N'dbo.Tmp_DATOSCOMPARATIVA', N'DATOSCOMPARATIVA', 'OBJECT' 
GO
ALTER TABLE dbo.DATOSCOMPARATIVA ADD CONSTRAINT
	PK_DATOSCOMPARATIVA PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.DATOSCOMPARATIVA ADD CONSTRAINT
	fk_datoscomparativamodelodato FOREIGN KEY
	(
	REFMODELODATO
	) REFERENCES dbo.MODELOSDATOS
	(
	CODIGO
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.DATOSCOMPARATIVA ADD CONSTRAINT
	fk_datoscomparativalcomparativa FOREIGN KEY
	(
	REFLCOMPARATIVA
	) REFERENCES dbo.LCOMPARATIVAS
	(
	ID
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
GO

Update VariablesGlobales Set Valor = '1.0.3.6' where Clave = 'DB_Version';
PRINT 'DB_Version: 1.0.3.6';