
PRINT 'Modificando CITAS para incluir IDEntregaCuenta con referencia a EntregasCuenta y bit PagadoConCredito '
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS ADD
	IDEntregaCuenta bigint NULL,
	PagadoConCredito bit NULL
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	DF_CITAS_PagadoConCredito DEFAULT 0 FOR PagadoConCredito
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	FK_CITAS_EntregasCuenta FOREIGN KEY
	(
	IDEntregaCuenta
	) REFERENCES dbo.EntregasCuenta
	(
	IDEntregaCuenta
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 	
GO
COMMIT



PRINT 'Modificando EntregasCuenta para incluir PagadoConCredito bit e IDFormaPago'
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO
ALTER TABLE dbo.EntregasCuenta ADD
	PagadoConCredito bit NULL,
	IDFormaPago varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
ALTER TABLE dbo.EntregasCuenta ADD CONSTRAINT
	DF_EntregasCuenta_PagadoConCredito DEFAULT 0 FOR PagadoConCredito
GO
ALTER TABLE dbo.EntregasCuenta ADD CONSTRAINT
	FK_EntregasCuenta_FORMASPAGO FOREIGN KEY
	(
	IDFormaPago
	) REFERENCES dbo.FORMASPAGO
	(
	CODIGO
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
Update EntregasCuenta SET PagadoConCredito=0 WHERE PagadoConCredito IS null
Update CITAS SET PagadoConCredito=0 WHERE PagadoConCredito IS null



PRINT 'Modificando FACTURAS para incluir IDEntregaCuenta con referencia a EntregasCuenta y bit PagadoConCredito '
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FACTURAS ADD
	IDEntregaCuenta bigint NULL,
	PagadoConCredito bit NULL
GO
ALTER TABLE dbo.FACTURAS ADD CONSTRAINT
	DF_FACTURAS_PagadoConCredito DEFAULT 0 FOR PagadoConCredito
GO
ALTER TABLE dbo.FACTURAS ADD CONSTRAINT
	FK_FACTURAS_EntregasCuenta FOREIGN KEY
	(
	IDEntregaCuenta
	) REFERENCES dbo.EntregasCuenta
	(
	IDEntregaCuenta
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 	
GO
COMMIT
Update FACTURAS SET PagadoConCredito=0 WHERE PagadoConCredito IS null

PRINT 'Modificando N_Ticket para incluir IDEntregaCuenta con referencia a EntregasCuenta y bit PagadoConCredito '
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket ADD
	IDEntregaCuenta bigint NULL,
	PagadoConCredito bit NULL
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	DF_N_Ticket_PagadoConCredito DEFAULT 0 FOR PagadoConCredito
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	FK_N_Ticket_EntregasCuenta FOREIGN KEY
	(
	IDEntregaCuenta
	) REFERENCES dbo.EntregasCuenta
	(
	IDEntregaCuenta
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 	
GO
COMMIT
Update N_Ticket SET PagadoConCredito=0 WHERE PagadoConCredito IS null

PRINT 'Modificando N_Factura para incluir IDEntregaCuenta con referencia a EntregasCuenta y bit PagadoConCredito '
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Factura ADD
	IDEntregaCuenta bigint NULL,
	PagadoConCredito bit NULL
GO
ALTER TABLE dbo.N_Factura ADD CONSTRAINT
	DF_N_Factura_PagadoConCredito DEFAULT 0 FOR PagadoConCredito
GO
ALTER TABLE dbo.N_Factura ADD CONSTRAINT
	FK_N_Factura_EntregasCuenta FOREIGN KEY
	(
	IDEntregaCuenta
	) REFERENCES dbo.EntregasCuenta
	(
	IDEntregaCuenta
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 	
GO
COMMIT
Update N_Factura SET PagadoConCredito=0 WHERE PagadoConCredito IS null



PRINT 'Modificando RECIBOS para incluir IDEntregaCuenta con referencia a EntregasCuenta y bit PagadoConCredito '
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RECIBOS ADD
	IDEntregaCuenta bigint NULL,
	PagadoConCredito bit NULL
GO
ALTER TABLE dbo.RECIBOS ADD CONSTRAINT
	DF_RECIBOS_PagadoConCredito DEFAULT 0 FOR PagadoConCredito
GO
ALTER TABLE dbo.RECIBOS ADD CONSTRAINT
	FK_RECIBOS_EntregasCuenta FOREIGN KEY
	(
	IDEntregaCuenta
	) REFERENCES dbo.EntregasCuenta
	(
	IDEntregaCuenta
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 	
GO
COMMIT
Update RECIBOS SET PagadoConCredito=0 WHERE PagadoConCredito IS null
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HISTORIALES_REVISIONES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[HISTORIALES_REVISIONES](
	[ID_Revision] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_Historial] [int] NOT NULL,
	[REFPACIENTE] [int] NULL,
	[REFMEDICO] [int] NULL,
	[MEDICO] [nvarchar](50) NULL,
	[FECHA] [datetime] NOT NULL,
	[MOTIVO] [nvarchar](max) NULL,
	[ANTECEDENTES] [nvarchar](max) NULL,
	[EXPLORACION] [nvarchar](max) NULL,
	[COMPLEMENTARIAS] [nvarchar](max) NULL,
	[JUICIO] [nvarchar](max) NULL,
	[TRATAMIENTO] [nvarchar](max) NULL,
	[COMENTARIOS] [nvarchar](max) NULL,
	[OTROS] [nvarchar](max) NULL,
	[REFDIAGNOSTICO] [int] NULL,
 CONSTRAINT [PK_HISTORIALES_REVISIONES] PRIMARY KEY CLUSTERED 
(
	[ID_Revision] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  ForeignKey [FK_HISTORIALES_REVISIONES_HISTORIALES]    Script Date: 02/01/2014 12:02:50 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HISTORIALES_REVISIONES_HISTORIALES]') AND parent_object_id = OBJECT_ID(N'[dbo].[HISTORIALES_REVISIONES]'))
ALTER TABLE [dbo].[HISTORIALES_REVISIONES]  WITH CHECK ADD  CONSTRAINT [FK_HISTORIALES_REVISIONES_HISTORIALES] FOREIGN KEY([ID_Historial])
REFERENCES [dbo].[HISTORIALES] ([CHISTORIAL])
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HISTORIALES_REVISIONES_HISTORIALES]') AND parent_object_id = OBJECT_ID(N'[dbo].[HISTORIALES_REVISIONES]'))
ALTER TABLE [dbo].[HISTORIALES_REVISIONES] CHECK CONSTRAINT [FK_HISTORIALES_REVISIONES_HISTORIALES]
GO
/****** Object:  ForeignKey [FK_HISTORIALES_REVISIONES_MEDICOS]    Script Date: 02/01/2014 12:02:50 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HISTORIALES_REVISIONES_MEDICOS]') AND parent_object_id = OBJECT_ID(N'[dbo].[HISTORIALES_REVISIONES]'))
ALTER TABLE [dbo].[HISTORIALES_REVISIONES]  WITH CHECK ADD  CONSTRAINT [FK_HISTORIALES_REVISIONES_MEDICOS] FOREIGN KEY([REFMEDICO])
REFERENCES [dbo].[MEDICOS] ([CMEDICO])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HISTORIALES_REVISIONES_MEDICOS]') AND parent_object_id = OBJECT_ID(N'[dbo].[HISTORIALES_REVISIONES]'))
ALTER TABLE [dbo].[HISTORIALES_REVISIONES] CHECK CONSTRAINT [FK_HISTORIALES_REVISIONES_MEDICOS]
GO
/****** Object:  ForeignKey [FK_HISTORIALES_REVISIONES_PACIENTES]    Script Date: 02/01/2014 12:02:50 ******/
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HISTORIALES_REVISIONES_PACIENTES]') AND parent_object_id = OBJECT_ID(N'[dbo].[HISTORIALES_REVISIONES]'))
ALTER TABLE [dbo].[HISTORIALES_REVISIONES]  WITH CHECK ADD  CONSTRAINT [FK_HISTORIALES_REVISIONES_PACIENTES] FOREIGN KEY([REFPACIENTE])
REFERENCES [dbo].[PACIENTES] ([CPACIENTE])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_HISTORIALES_REVISIONES_PACIENTES]') AND parent_object_id = OBJECT_ID(N'[dbo].[HISTORIALES_REVISIONES]'))
ALTER TABLE [dbo].[HISTORIALES_REVISIONES] CHECK CONSTRAINT [FK_HISTORIALES_REVISIONES_PACIENTES]
GO



Update VariablesGlobales Set Valor = '1.0.3.1' where Clave = 'DB_Version';
PRINT 'DB_Version: 1.0.3.1'