/* BEGIN Annadido campo IDAccionOrigen a los Presupuestos para poder eliminar */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.d_PresupuestoLineas ADD
	IDAccionOrigen bigint NULL
GO
ALTER TABLE dbo.d_PresupuestoLineas ADD CONSTRAINT
	FK_d_PresupuestoLineas_d_Acciones FOREIGN KEY
	(
	IDAccionOrigen
	) REFERENCES dbo.d_Acciones
	(
	IDAccion
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT


/*BEGIN Creacion de tabla Comunicaciones*/
GO
/****** Object:  Table [dbo].[Comunicaciones]    Script Date: 02/16/2011 17:29:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comunicaciones](
	[ID_Comunicacion] [bigint] IDENTITY(1,1) NOT NULL,
	[eTipo] [int] NULL,
	[FechaEnvio] [datetime] NULL,
	[ID_UsuarioEmisor] [int] NULL,
	[ID_PacienteDestino] [int] NULL,
	[NombreUsuarioEmisor] [nvarchar](50) NULL,
	[NombrePacienteDestino] [nvarchar](50) NULL,
	[Contenido] [nvarchar](max) NULL,
 CONSTRAINT [PK_Comunicaciones] PRIMARY KEY CLUSTERED 
(
	[ID_Comunicacion] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Comunicaciones]  WITH CHECK ADD  CONSTRAINT [FK_Comunicaciones_PACIENTES] FOREIGN KEY([ID_PacienteDestino])
REFERENCES [dbo].[PACIENTES] ([CPACIENTE])
GO
ALTER TABLE [dbo].[Comunicaciones] CHECK CONSTRAINT [FK_Comunicaciones_PACIENTES]
GO
ALTER TABLE [dbo].[Comunicaciones]  WITH CHECK ADD  CONSTRAINT [FK_Comunicaciones_USUARIOS] FOREIGN KEY([ID_UsuarioEmisor])
REFERENCES [dbo].[USUARIOS] ([CODIGO])
GO
ALTER TABLE [dbo].[Comunicaciones] CHECK CONSTRAINT [FK_Comunicaciones_USUARIOS]

/*END Creacion de tabla Comunicaciones */




/*BEGIN Modificacion de la tabla USUARIOS para configuracion personalizada */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.USUARIOS ADD
	CONFIGURACIONXML xml NULL
GO
COMMIT
GO
/*END Modificacion de la tabla USUARIOS para configuracion personalizada */




/*BEGIN Modificar longitud de CONCEPTO de la tabla LineasFacturas de 90 a MAX*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT FK_LINEASFACTURAS_CITAS
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT fklineasfacturas
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT fk_lineasfacturas
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT DF__LINEASFAC__CANTI__3C69FB99
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT DF__LINEASFAC__TIPOI__3D5E1FD2
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT DF_LINEASFACTURAS_Descuento
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT DF_LINEASFACTURAS_ImporteOriginal
GO
CREATE TABLE dbo.Tmp_LINEASFACTURAS
	(
	IDLINEAFACTURA int NOT NULL IDENTITY (1, 1) NOT FOR REPLICATION,
	CONCEPTO nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IMPORTE decimal(18, 2) NULL,
	REFFACTURA int NOT NULL,
	REFCONCEPTO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CANTIDAD real NOT NULL,
	TIPOIVA real NOT NULL,
	ID_Cita int NULL,
	Descuento float(53) NULL,
	ImporteOriginal float(53) NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_LINEASFACTURAS ADD CONSTRAINT
	DF__LINEASFAC__CANTI__3C69FB99 DEFAULT ((1)) FOR CANTIDAD
GO
ALTER TABLE dbo.Tmp_LINEASFACTURAS ADD CONSTRAINT
	DF__LINEASFAC__TIPOI__3D5E1FD2 DEFAULT ((0)) FOR TIPOIVA
GO
ALTER TABLE dbo.Tmp_LINEASFACTURAS ADD CONSTRAINT
	DF_LINEASFACTURAS_Descuento DEFAULT ((0)) FOR Descuento
GO
ALTER TABLE dbo.Tmp_LINEASFACTURAS ADD CONSTRAINT
	DF_LINEASFACTURAS_ImporteOriginal DEFAULT ((0)) FOR ImporteOriginal
GO
SET IDENTITY_INSERT dbo.Tmp_LINEASFACTURAS ON
GO
IF EXISTS(SELECT * FROM dbo.LINEASFACTURAS)
	 EXEC('INSERT INTO dbo.Tmp_LINEASFACTURAS (IDLINEAFACTURA, CONCEPTO, IMPORTE, REFFACTURA, REFCONCEPTO, CANTIDAD, TIPOIVA, ID_Cita, Descuento, ImporteOriginal)
		SELECT IDLINEAFACTURA, CONVERT(nvarchar(MAX), CONCEPTO), IMPORTE, REFFACTURA, REFCONCEPTO, CANTIDAD, TIPOIVA, ID_Cita, Descuento, ImporteOriginal FROM dbo.LINEASFACTURAS WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_LINEASFACTURAS OFF
GO
DROP TABLE dbo.LINEASFACTURAS
GO
EXECUTE sp_rename N'dbo.Tmp_LINEASFACTURAS', N'LINEASFACTURAS', 'OBJECT' 
GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	PK_LINEASFACTURAS PRIMARY KEY CLUSTERED 
	(
	IDLINEAFACTURA
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	fk_lineasfacturas FOREIGN KEY
	(
	REFCONCEPTO
	) REFERENCES dbo.CONCEPTOSFRA
	(
	CODIGO
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	fklineasfacturas FOREIGN KEY
	(
	REFFACTURA
	) REFERENCES dbo.FACTURAS
	(
	IDFACTURA
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	FK_LINEASFACTURAS_CITAS FOREIGN KEY
	(
	ID_Cita
	) REFERENCES dbo.CITAS
	(
	IDCITA
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
/*END Modificar longitud de CONCEPTO de la tabla LineasFacturas de 90 a MAX*/


/*BEGIN Modificar longitud de DESCRIPCION de la tabla LINEASCITAS de 150 a MAX*/
/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT FK_LineasCitas_Citas
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT FK_LineasCitas_d_PresupuestoLineas
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT DF_LineasCitas_DESCRIPCION
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT DF_LineasCitas_Cantidad
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT DF_LineasCitas_ImporteClinica
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT DF_LineasCitas_ImporteDr
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT DF_LineasCitas_DescuentoPercent
GO
CREATE TABLE dbo.Tmp_LineasCitas
	(
	IdLinea bigint NOT NULL IDENTITY (1, 1),
	IdCita int NOT NULL,
	RefConcepto varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPCION nvarchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	Cantidad float(53) NOT NULL,
	ImporteClinica float(53) NOT NULL,
	ImporteDr float(53) NOT NULL,
	Duracion datetime NULL,
	RefLineaPresupuestoDental bigint NULL,
	DescuentoPercent float(53) NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_LineasCitas ADD CONSTRAINT
	DF_LineasCitas_DESCRIPCION DEFAULT ('') FOR DESCRIPCION
GO
ALTER TABLE dbo.Tmp_LineasCitas ADD CONSTRAINT
	DF_LineasCitas_Cantidad DEFAULT ((1)) FOR Cantidad
GO
ALTER TABLE dbo.Tmp_LineasCitas ADD CONSTRAINT
	DF_LineasCitas_ImporteClinica DEFAULT ((0)) FOR ImporteClinica
GO
ALTER TABLE dbo.Tmp_LineasCitas ADD CONSTRAINT
	DF_LineasCitas_ImporteDr DEFAULT ((0)) FOR ImporteDr
GO
ALTER TABLE dbo.Tmp_LineasCitas ADD CONSTRAINT
	DF_LineasCitas_DescuentoPercent DEFAULT ((0)) FOR DescuentoPercent
GO
SET IDENTITY_INSERT dbo.Tmp_LineasCitas ON
GO
IF EXISTS(SELECT * FROM dbo.LineasCitas)
	 EXEC('INSERT INTO dbo.Tmp_LineasCitas (IdLinea, IdCita, RefConcepto, DESCRIPCION, Cantidad, ImporteClinica, ImporteDr, Duracion, RefLineaPresupuestoDental, DescuentoPercent)
		SELECT IdLinea, IdCita, RefConcepto, CONVERT(nvarchar(MAX), DESCRIPCION), Cantidad, ImporteClinica, ImporteDr, Duracion, RefLineaPresupuestoDental, DescuentoPercent FROM dbo.LineasCitas WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_LineasCitas OFF
GO
DROP TABLE dbo.LineasCitas
GO
EXECUTE sp_rename N'dbo.Tmp_LineasCitas', N'LineasCitas', 'OBJECT' 
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	PK_LineasCitas PRIMARY KEY CLUSTERED 
	(
	IdLinea,
	IdCita
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	FK_LineasCitas_d_PresupuestoLineas FOREIGN KEY
	(
	RefLineaPresupuestoDental
	) REFERENCES dbo.d_PresupuestoLineas
	(
	IDPresupuestoLinea
	) ON UPDATE  NO ACTION 
	 ON DELETE  SET NULL 
	
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	FK_LineasCitas_Citas FOREIGN KEY
	(
	IdCita
	) REFERENCES dbo.CITAS
	(
	IDCITA
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT

/*END Modificar longitud de DESCRIPCION de la tabla LINEASCITAS de 150 a MAX*/

Update VariablesGlobales Set Valor = '1.0.1.3' where Clave = 'DB_Version';
