IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__CONCEPTOS__IMPOR__173876EA]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CONCEPTOSANALITICA] DROP CONSTRAINT [DF__CONCEPTOS__IMPOR__173876EA]
END

GO

/****** Object:  Table [dbo].[CONCEPTOSANALITICA]    Script Date: 09/22/2015 10:21:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONCEPTOSANALITICA]') AND type in (N'U'))
DROP TABLE [dbo].[CONCEPTOSANALITICA]
GO


/****** Object:  Table [dbo].[CONCEPTOSANALITICA]    Script Date: 09/22/2015 10:21:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CONCEPTOSANALITICA](
	[CODIGO] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CONCEPTO] [varchar](90) NULL,
	[IMPORTE] [real] NOT NULL,
	[NOTAS] [text] NULL,
	[COLOR] [varchar](24) NULL,
 CONSTRAINT [PK_CONCEPTOSANALITICA] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CONCEPTOSANALITICA] ADD  CONSTRAINT [DF__CONCEPTOS__IMPOR__173876EA]  DEFAULT ((0)) FOR [IMPORTE]
GO

Update VariablesGlobales Set Valor = '1.0.3.8' where Clave = 'DB_Version';
PRINT 'DB_Version: 1.0.3.8';
GO


