
/****** Object:  Table [dbo].[SALAS]    Script Date: 10/17/2011 15:40:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SALAS](
	[ID_SALA] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
	[Descripcion] [nvarchar](200) NULL,
	[ID_MEDICOJEFE] [int] NULL,
 CONSTRAINT [PK_SALAS] PRIMARY KEY CLUSTERED 
(
	[ID_SALA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO

/*ALTER TABLE dbo.SALAS SET (LOCK_ESCALATION = TABLE)
GO */

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS ADD
	ID_SALA int NULL
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	FK_CITAS_SALAS FOREIGN KEY
	(
	ID_SALA
	) REFERENCES dbo.SALAS
	(
	ID_SALA
	) ON UPDATE  CASCADE 
	 ON DELETE  SET NULL 
	
GO
/*
ALTER TABLE dbo.CITAS SET (LOCK_ESCALATION = TABLE)
GO
*/
COMMIT

/*BEGIN LineasCitas Annadir TOTAL y REFLineaFactura a las Lineas de Cita.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
--ALTER TABLE dbo.LINEASFACTURAS SET (LOCK_ESCALATION = TABLE)
--GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas ADD
	Total float(53) NULL,
	RefLineaFactura int NULL
GO
DECLARE @v sql_variant 
SET @v = N'Total incluyendo descuentos'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'LineasCitas', N'COLUMN', N'Total'
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	DF_LineasCitas_Total DEFAULT 0 FOR Total
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	FK_LineasCitas_LINEASFACTURAS FOREIGN KEY
	(
	RefLineaFactura
	) REFERENCES dbo.LINEASFACTURAS
	(
	IDLINEAFACTURA
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
/* ALTER TABLE dbo.LineasCitas SET (LOCK_ESCALATION = TABLE)*/
--GO
COMMIT
/*END LineasCitas Annadir TOTAL y REFLineaFactura a las Lineas de Cita.*/



/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS ADD
	TOTAL decimal(18, 0) NULL
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	DF_CITAS_TOTAL DEFAULT 0 FOR TOTAL
GO
/* ALTER TABLE dbo.CITAS SET (LOCK_ESCALATION = TABLE)*/
GO
COMMIT

/*ELiMINAR el Permiso duplicado Articulos*/
GO
DELETE FROM ROLESITEMS WHERE ID_ROLESITEM = 8;
GO




/*Begin Agregar referencia en LineasFacturas a LineasCita*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS ADD
	RefLineaCita bigint NULL
GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	FK_LINEASFACTURAS_LineasCitas FOREIGN KEY
	(
	RefLineaCita,
	ID_Cita
	) REFERENCES dbo.LineasCitas
	(
	IdLinea,
	IdCita
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
/*END Agregar referencia de LineasCita a LineaFactura*/


/*BEGIN Eliminara referencia inutul de lineasCitas a LineaFactur*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT FK_LineasCitas_LINEASFACTURAS
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas
	DROP COLUMN RefLineaFactura
GO
/*END Eliminar referencia inutil de LineasFacturas a Linea Citas*/
COMMIT
GO


/*BEGIN Agregar columna PorcientoCita a tabla Medico */

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.MEDICOS ADD
	PorcientoCita float(53) NULL
GO
ALTER TABLE dbo.MEDICOS ADD CONSTRAINT
	DF_MEDICOS_PorcientoCita DEFAULT 0 FOR PorcientoCita
GO
COMMIT

/*END Agregar columna PorcientoCita a tabla Medico */






/*BEGIN Creacion de las tablas 
 MEDICO_CONCEPTOFRA
 Liquidacion_Medico
 Liquidacion_Medico_Lineas
 */


/*BEGIN Eliminar FK_MEDICOS_CONCEPTOFRA_CONCEPTOSFRA*/

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MEDICOS_CONCEPTOFRA_CONCEPTOSFRA]') AND parent_object_id = OBJECT_ID(N'[dbo].[MEDICOS_CONCEPTOFRA]'))
ALTER TABLE dbo.MEDICOS_CONCEPTOFRA
	DROP CONSTRAINT FK_MEDICOS_CONCEPTOFRA_CONCEPTOSFRA
GO
COMMIT
BEGIN TRANSACTION
GO
COMMIT
/* END Eliminacion de FK_MEDICOS_CONCEPTOFRA_CONCEPTOSFRA */


/****** Object:  Table [dbo].[MEDICOS_CONCEPTOFRA]    Script Date: 12/29/2011 17:07:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MEDICOS_CONCEPTOFRA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[MEDICOS_CONCEPTOFRA](
	[CMEDICO] [int] NOT NULL,
	[CODIGO] [varchar](10) NOT NULL,
	[ImporteDto] [float] NULL,
	[ImportePorciento] [float] NULL,
 CONSTRAINT [PK_MEDICOS_CONCEPTOFRA] PRIMARY KEY CLUSTERED 
(
	[CMEDICO] ASC,
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Liquidacion_Medico]    Script Date: 01/05/2012 07:38:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Liquidacion_Medico](
	[ID_Liquidacion] [bigint] IDENTITY(1,1) NOT NULL,
	[Fecha] [datetime] NULL,
	[ID_Medico] [int] NULL,
	[ID_FormaPago] [varchar](10) NULL,
	[Importe] [float] NULL,
	[Descripcion] [nvarchar](200) NULL,
	[Notas] [nvarchar](200) NULL,
	[ID_Usuario] [int] NULL,
 CONSTRAINT [PK_Liquidacion_Medico] PRIMARY KEY CLUSTERED 
(
	[ID_Liquidacion] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Liquidacion_Medico_Linea]    Script Date: 01/05/2012 07:38:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Liquidacion_Medico_Linea](
	[Id_Linea_Liquidacion] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_Liquidacion] [bigint] NULL,
	[ID_LineaCita] [bigint] NULL,
	[Descripcion] [nvarchar](200) NULL,
	[Fecha] [datetime] NULL,
	[Importe] [float] NULL,
	[ID_Usuario] [nchar](10) NULL,
 CONSTRAINT [PK_Liquidacion_Medico_Linea] PRIMARY KEY CLUSTERED 
(
	[Id_Linea_Liquidacion] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_Liquidacion_Medico_MEDICOS]    Script Date: 01/05/2012 07:38:05 ******/
ALTER TABLE [dbo].[Liquidacion_Medico]  WITH CHECK ADD  CONSTRAINT [FK_Liquidacion_Medico_MEDICOS] FOREIGN KEY([ID_Medico])
REFERENCES [dbo].[MEDICOS] ([CMEDICO])
GO
ALTER TABLE [dbo].[Liquidacion_Medico] CHECK CONSTRAINT [FK_Liquidacion_Medico_MEDICOS]
GO
/****** Object:  ForeignKey [FK_Liquidacion_Medico_Linea_Liquidacion_Medico]    Script Date: 01/05/2012 07:38:05 ******/
ALTER TABLE [dbo].[Liquidacion_Medico_Linea]  WITH CHECK ADD  CONSTRAINT [FK_Liquidacion_Medico_Linea_Liquidacion_Medico] FOREIGN KEY([ID_Liquidacion])
REFERENCES [dbo].[Liquidacion_Medico] ([ID_Liquidacion])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Liquidacion_Medico_Linea] CHECK CONSTRAINT [FK_Liquidacion_Medico_Linea_Liquidacion_Medico]
GO




/*END Creacion de las tablas 
 MEDICO_CONCEPTOFRA
 Liquidacion_Medico
 Liquidacion_Medico_Lineas
 */
 
 /*BEGIN Annadir columna Liquidada_Medico en LineasCita*/
/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas ADD
	Liquidada_al_Medico bit NULL
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	DF_LineasCitas_Liquidada_al_Medico DEFAULT 0 FOR Liquidada_al_Medico
GO
COMMIT
 

 /*END Annadir columna Liquidada_Medico en LineasCita*/


 /*BEGIN Modificar los tamannos de 
TLFNO (200 carac.), 
movil (200 carac), 
localidad (200 carac) 
provincia (300 carac).
En PACIENTES
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__PAGOBANCO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__DEFUN
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__SOCIO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF__PACIENTES__ACTIV
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_WEB
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_EMAIL
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_CODIGOPROPIO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_BENEFICIARIOCODIGOSOCIO
GO
ALTER TABLE dbo.PACIENTES
	DROP CONSTRAINT DF_PACIENTES_BENEFICIARIOPARENTESCO
GO
CREATE TABLE dbo.Tmp_PACIENTES
	(
	NOMBRE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	APELLIDO1 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	APELLIDO2 varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DOMICILIO varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TLFNO nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MOVIL nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROFESION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOCALIDAD varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CP varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFEMPRESA int NULL,
	DNI varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHAN datetime NULL,
	OBSERVACIONES varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PROVINCIA varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NSS varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PUESTO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REGIMEN varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TARJETASANITARIA varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFMUTUA int NULL,
	CPACIENTE int NOT NULL,
	SEXO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHAALTA datetime NULL,
	TUTOR varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAGOBANCO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ENTIDAD varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	OFICINA varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DC varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TITULAR varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CUENTA varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DEFUNCION varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NIE varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PASAPORTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFPAIS int NOT NULL,
	FOTO image NULL,
	FOTOGRAFIA varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SOCIO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ACTIVO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFFORMAPAGO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FECHABAJA datetime NULL,
	CONOCIO varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WEB varchar(250) NOT NULL,
	EMAIL varchar(250) NOT NULL,
	CODIGOPROPIO varchar(50) NOT NULL,
	BENEFICIARIOCODIGOSOCIO int NOT NULL,
	BENEFICIARIOPARENTESCO varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__PAGOBANCO DEFAULT ('N') FOR PAGOBANCO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__DEFUN DEFAULT ('N') FOR DEFUNCION
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__SOCIO DEFAULT ('N') FOR SOCIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF__PACIENTES__ACTIV DEFAULT ('S') FOR ACTIVO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_WEB DEFAULT ('') FOR WEB
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_EMAIL DEFAULT ('') FOR EMAIL
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_CODIGOPROPIO DEFAULT ('') FOR CODIGOPROPIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_BENEFICIARIOCODIGOSOCIO DEFAULT ('') FOR BENEFICIARIOCODIGOSOCIO
GO
ALTER TABLE dbo.Tmp_PACIENTES ADD CONSTRAINT
	DF_PACIENTES_BENEFICIARIOPARENTESCO DEFAULT ('') FOR BENEFICIARIOPARENTESCO
GO
IF EXISTS(SELECT * FROM dbo.PACIENTES)
	 EXEC('INSERT INTO dbo.Tmp_PACIENTES (NOMBRE, APELLIDO1, APELLIDO2, DOMICILIO, TLFNO, MOVIL, PROFESION, LOCALIDAD, CP, REFEMPRESA, DNI, FECHAN, OBSERVACIONES, PROVINCIA, NSS, PUESTO, REGIMEN, TARJETASANITARIA, REFMUTUA, CPACIENTE, SEXO, FECHAALTA, TUTOR, PAGOBANCO, ENTIDAD, OFICINA, DC, TITULAR, CUENTA, DEFUNCION, NIE, PASAPORTE, REFPAIS, FOTO, FOTOGRAFIA, SOCIO, ACTIVO, REFFORMAPAGO, FECHABAJA, CONOCIO, WEB, EMAIL, CODIGOPROPIO, BENEFICIARIOCODIGOSOCIO, BENEFICIARIOPARENTESCO)
		SELECT NOMBRE, APELLIDO1, APELLIDO2, DOMICILIO, TLFNO, MOVIL, PROFESION, LOCALIDAD, CP, REFEMPRESA, DNI, FECHAN, OBSERVACIONES, PROVINCIA, NSS, PUESTO, REGIMEN, TARJETASANITARIA, REFMUTUA, CPACIENTE, SEXO, FECHAALTA, TUTOR, PAGOBANCO, ENTIDAD, OFICINA, DC, TITULAR, CUENTA, DEFUNCION, NIE, PASAPORTE, REFPAIS, FOTO, FOTOGRAFIA, SOCIO, ACTIVO, REFFORMAPAGO, FECHABAJA, CONOCIO, WEB, EMAIL, CODIGOPROPIO, BENEFICIARIOCODIGOSOCIO, BENEFICIARIOPARENTESCO FROM dbo.PACIENTES WITH (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.d_Odontogramas
	DROP CONSTRAINT FK_d_Odontogramas_PACIENTES
GO
ALTER TABLE dbo.PagosPaciente
	DROP CONSTRAINT FK_PagosCliente_PACIENTES
GO
ALTER TABLE dbo.AntecedentesDiagnosticos
	DROP CONSTRAINT FK_AntecedentesDiagnosticos_PACIENTES
GO
ALTER TABLE dbo.N_Partes_Asistencia
	DROP CONSTRAINT FK_N_Partes_Asistencia_PACIENTES
GO
ALTER TABLE dbo.N_Procesos
	DROP CONSTRAINT FK_N_Procesos_PACIENTES
GO
ALTER TABLE dbo.RECIBOS
	DROP CONSTRAINT FK_RECIBOS_PACIENTES
GO
ALTER TABLE dbo.EntregasCuenta
	DROP CONSTRAINT FK_EntregasCuenta_PACIENTES
GO
ALTER TABLE dbo.RECETAS
	DROP CONSTRAINT fkrecetaspaciente
GO
ALTER TABLE dbo.PRESUPUESTOS
	DROP CONSTRAINT fkpresupuestopaciente
GO
ALTER TABLE dbo.LMUTUAS
	DROP CONSTRAINT fk_lmutuas_pacientes
GO
ALTER TABLE dbo.N_Factura
	DROP CONSTRAINT FK_N_Factura_N_Pacientes
GO
ALTER TABLE dbo.LINEASALARMA
	DROP CONSTRAINT fklineasalarmapaciente
GO
ALTER TABLE dbo.LEMPRESAS
	DROP CONSTRAINT fk_lempresaspacientes
GO
ALTER TABLE dbo.INFORMACIONPRIMARIA
	DROP CONSTRAINT fk_informacionprimariapaciente
GO
ALTER TABLE dbo.IMAGENES
	DROP CONSTRAINT fkimagenespaciente
GO
ALTER TABLE dbo.HISTORIALES
	DROP CONSTRAINT fkhistorialespaciente
GO
ALTER TABLE dbo.FICHEROS
	DROP CONSTRAINT fk_ficheros
GO
ALTER TABLE dbo.FACTURAS
	DROP CONSTRAINT fkfacturaspaciente
GO
ALTER TABLE dbo.DERIVACIONES
	DROP CONSTRAINT fk_derivacionespaciente
GO
ALTER TABLE dbo.COMPARATIVAS
	DROP CONSTRAINT fk_comparativaspaciente
GO
ALTER TABLE dbo.AUDIOMETRIAS
	DROP CONSTRAINT fk_audiometrias
GO
ALTER TABLE dbo.ANALITICAS
	DROP CONSTRAINT fk_analiticapaciente
GO
ALTER TABLE dbo.Asociados
	DROP CONSTRAINT FK_Asociados_PACIENTES
GO
ALTER TABLE dbo.Asociados
	DROP CONSTRAINT FK_Asociados_PACIENTES1
GO
ALTER TABLE dbo.N_Ticket
	DROP CONSTRAINT FK_N_Ticket_N_Pacientes
GO
ALTER TABLE dbo.Comunicaciones
	DROP CONSTRAINT FK_Comunicaciones_PACIENTES
GO
DROP TABLE dbo.PACIENTES
GO
EXECUTE sp_rename N'dbo.Tmp_PACIENTES', N'PACIENTES', 'OBJECT' 
GO
ALTER TABLE dbo.PACIENTES ADD CONSTRAINT
	PK_PACIENTES PRIMARY KEY CLUSTERED 
	(
	CPACIENTE
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Comunicaciones ADD CONSTRAINT
	FK_Comunicaciones_PACIENTES FOREIGN KEY
	(
	ID_PacienteDestino
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Ticket ADD CONSTRAINT
	FK_N_Ticket_N_Pacientes FOREIGN KEY
	(
	ID_Cliente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Asociados ADD CONSTRAINT
	FK_Asociados_PACIENTES FOREIGN KEY
	(
	IDPacienteBeneficiario
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.Asociados ADD CONSTRAINT
	FK_Asociados_PACIENTES1 FOREIGN KEY
	(
	IDPacienteOrigen
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ANALITICAS ADD CONSTRAINT
	fk_analiticapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AUDIOMETRIAS ADD CONSTRAINT
	fk_audiometrias FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.COMPARATIVAS ADD CONSTRAINT
	fk_comparativaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DERIVACIONES ADD CONSTRAINT
	fk_derivacionespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FACTURAS ADD CONSTRAINT
	fkfacturaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FICHEROS ADD CONSTRAINT
	fk_ficheros FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.HISTORIALES ADD CONSTRAINT
	fkhistorialespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.IMAGENES ADD CONSTRAINT
	fkimagenespaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.INFORMACIONPRIMARIA ADD CONSTRAINT
	fk_informacionprimariapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LEMPRESAS ADD CONSTRAINT
	fk_lempresaspacientes FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASALARMA ADD CONSTRAINT
	fklineasalarmapaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Factura ADD CONSTRAINT
	FK_N_Factura_N_Pacientes FOREIGN KEY
	(
	ID_Cliente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LMUTUAS ADD CONSTRAINT
	fk_lmutuas_pacientes FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PRESUPUESTOS ADD CONSTRAINT
	fkpresupuestopaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RECETAS ADD CONSTRAINT
	fkrecetaspaciente FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.EntregasCuenta ADD CONSTRAINT
	FK_EntregasCuenta_PACIENTES FOREIGN KEY
	(
	IDPaciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RECIBOS ADD CONSTRAINT
	FK_RECIBOS_PACIENTES FOREIGN KEY
	(
	REFPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Procesos ADD CONSTRAINT
	FK_N_Procesos_PACIENTES FOREIGN KEY
	(
	ID_Paciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.N_Partes_Asistencia ADD CONSTRAINT
	FK_N_Partes_Asistencia_PACIENTES FOREIGN KEY
	(
	ID_Paciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AntecedentesDiagnosticos ADD CONSTRAINT
	FK_AntecedentesDiagnosticos_PACIENTES FOREIGN KEY
	(
	CPACIENTE
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PagosPaciente ADD CONSTRAINT
	FK_PagosCliente_PACIENTES FOREIGN KEY
	(
	IDPaciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.d_Odontogramas ADD CONSTRAINT
	FK_d_Odontogramas_PACIENTES FOREIGN KEY
	(
	IDPaciente
	) REFERENCES dbo.PACIENTES
	(
	CPACIENTE
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT

/*END Modificar los tamannos de 
TLFNO (200 carac.), 
movil (200 carac), 
localidad (200 carac) 
provincia (300 carac).
En PACIENTES
*/






/*BEGIN Cambiar el Total de la CITA de Decimal(18,0) a Decimal(18,2) a */

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT FK_CITAS_N_Procesos
GO

COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT FK_CITAS_SALAS
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT fkmedico
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT fk_citas
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT DF__CITAS__CONFIRMAD__108B795B
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT DF__CITAS__BANCO__117F9D94
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT DF__CITAS__PAGADA__1273C1CD
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT DF__CITAS__ATENDIDO__1367E606
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT DF__CITAS__REFPROCED__145C0A3F
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT DF_CITAS_Descuento
GO
ALTER TABLE dbo.CITAS
	DROP CONSTRAINT DF_CITAS_TOTAL
GO
CREATE TABLE dbo.Tmp_CITAS
	(
	IDCITA int NOT NULL IDENTITY (1, 1) NOT FOR REPLICATION,
	REFPACIENTE int NULL,
	FECHA datetime NULL,
	HORA datetime NULL,
	CONFIRMADA varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	NOTAS text COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFMEDICO int NULL,
	PACIENTE varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IMPORTEDR decimal(18, 2) NULL,
	IMPORTECL decimal(18, 2) NULL,
	CONTINUA varchar(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FALTA varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BANCO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PAGADA varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFRECIBO int NULL,
	ATENDIDO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REFFRA int NULL,
	REFFORMAPAGO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HORAFIN datetime NULL,
	FECHACOBRO datetime NULL,
	REFPROCEDENCIA int NULL,
	ID_Proceso bigint NULL,
	EstadoRecurrencia int NULL,
	FechaUltimoEstadoRecurrencia datetime NULL,
	Descuento float(53) NULL,
	ID_SALA int NULL,
	TOTAL decimal(18, 2) NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_CITAS ADD CONSTRAINT
	DF__CITAS__CONFIRMAD__108B795B DEFAULT ('S') FOR CONFIRMADA
GO
ALTER TABLE dbo.Tmp_CITAS ADD CONSTRAINT
	DF__CITAS__BANCO__117F9D94 DEFAULT ('N') FOR BANCO
GO
ALTER TABLE dbo.Tmp_CITAS ADD CONSTRAINT
	DF__CITAS__PAGADA__1273C1CD DEFAULT ('N') FOR PAGADA
GO
ALTER TABLE dbo.Tmp_CITAS ADD CONSTRAINT
	DF__CITAS__ATENDIDO__1367E606 DEFAULT ('N') FOR ATENDIDO
GO
ALTER TABLE dbo.Tmp_CITAS ADD CONSTRAINT
	DF__CITAS__REFPROCED__145C0A3F DEFAULT ((-1)) FOR REFPROCEDENCIA
GO
ALTER TABLE dbo.Tmp_CITAS ADD CONSTRAINT
	DF_CITAS_Descuento DEFAULT ((0)) FOR Descuento
GO
ALTER TABLE dbo.Tmp_CITAS ADD CONSTRAINT
	DF_CITAS_TOTAL DEFAULT ((0)) FOR TOTAL
GO
SET IDENTITY_INSERT dbo.Tmp_CITAS ON
GO
IF EXISTS(SELECT * FROM dbo.CITAS)
	 EXEC('INSERT INTO dbo.Tmp_CITAS (IDCITA, REFPACIENTE, FECHA, HORA, CONFIRMADA, NOTAS, REFMEDICO, PACIENTE, IMPORTEDR, IMPORTECL, CONTINUA, FALTA, BANCO, PAGADA, REFRECIBO, ATENDIDO, REFFRA, REFFORMAPAGO, HORAFIN, FECHACOBRO, REFPROCEDENCIA, ID_Proceso, EstadoRecurrencia, FechaUltimoEstadoRecurrencia, Descuento, ID_SALA, TOTAL)
		SELECT IDCITA, REFPACIENTE, FECHA, HORA, CONFIRMADA, NOTAS, REFMEDICO, PACIENTE, IMPORTEDR, IMPORTECL, CONTINUA, FALTA, BANCO, PAGADA, REFRECIBO, ATENDIDO, REFFRA, REFFORMAPAGO, HORAFIN, FECHACOBRO, REFPROCEDENCIA, ID_Proceso, EstadoRecurrencia, FechaUltimoEstadoRecurrencia, Descuento, ID_SALA, TOTAL FROM dbo.CITAS WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_CITAS OFF
GO
ALTER TABLE dbo.d_PresupuestoLineas
	DROP CONSTRAINT FK_d_PresupuestoLineas_Citas
GO
ALTER TABLE dbo.LINEASFACTURAS
	DROP CONSTRAINT FK_LINEASFACTURAS_CITAS
GO
ALTER TABLE dbo.LineasCitas
	DROP CONSTRAINT FK_LineasCitas_Citas
GO
DROP TABLE dbo.CITAS
GO
EXECUTE sp_rename N'dbo.Tmp_CITAS', N'CITAS', 'OBJECT' 
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	PK_CITAS PRIMARY KEY CLUSTERED 
	(
	IDCITA
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	fk_citas FOREIGN KEY
	(
	REFFORMAPAGO
	) REFERENCES dbo.FORMASPAGO
	(
	CODIGO
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	fkmedico FOREIGN KEY
	(
	REFMEDICO
	) REFERENCES dbo.MEDICOS
	(
	CMEDICO
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	FK_CITAS_SALAS FOREIGN KEY
	(
	ID_SALA
	) REFERENCES dbo.SALAS
	(
	ID_SALA
	) ON UPDATE  CASCADE 
	 ON DELETE  SET NULL 
	
GO
ALTER TABLE dbo.CITAS ADD CONSTRAINT
	FK_CITAS_N_Procesos FOREIGN KEY
	(
	ID_Proceso
	) REFERENCES dbo.N_Procesos
	(
	ID_Proceso
	) ON UPDATE  CASCADE 
	 ON DELETE  SET NULL 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LineasCitas ADD CONSTRAINT
	FK_LineasCitas_Citas FOREIGN KEY
	(
	IdCita
	) REFERENCES dbo.CITAS
	(
	IDCITA
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LINEASFACTURAS ADD CONSTRAINT
	FK_LINEASFACTURAS_CITAS FOREIGN KEY
	(
	ID_Cita
	) REFERENCES dbo.CITAS
	(
	IDCITA
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.d_PresupuestoLineas ADD CONSTRAINT
	FK_d_PresupuestoLineas_Citas FOREIGN KEY
	(
	IDCITA
	) REFERENCES dbo.CITAS
	(
	IDCITA
	) ON UPDATE  NO ACTION 
	 ON DELETE  SET NULL 
	
GO
COMMIT

/*END Cambiar el Total de la CITA de Decimal(18,0) a Decimal(18,2) a */














Update VariablesGlobales Set Valor = '1.0.1.5' where Clave = 'DB_Version';