USE [master]
GO

/****** Object:  Database [siesta]    Script Date: 11/04/2016 12:20:44 ******/
CREATE DATABASE [siesta] ON  PRIMARY 
( NAME = N'siesta', FILENAME = N'Direction\siesta.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'siesta_log', FILENAME = N'Direction\siesta_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [siesta] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [siesta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [siesta] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [siesta] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [siesta] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [siesta] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [siesta] SET ARITHABORT OFF 
GO

ALTER DATABASE [siesta] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [siesta] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [siesta] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [siesta] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [siesta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [siesta] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [siesta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [siesta] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [siesta] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [siesta] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [siesta] SET  DISABLE_BROKER 
GO

ALTER DATABASE [siesta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [siesta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [siesta] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [siesta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [siesta] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [siesta] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [siesta] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [siesta] SET  READ_WRITE 
GO

ALTER DATABASE [siesta] SET RECOVERY FULL 
GO

ALTER DATABASE [siesta] SET  MULTI_USER 
GO

ALTER DATABASE [siesta] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [siesta] SET DB_CHAINING OFF 
GO


