/* Annadir campo N19 a tabla FACTURAS*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FACTURAS ADD
	N19 nvarchar(1) NULL
GO
COMMIT

Update VariablesGlobales Set Valor = '1.0.0.6' where Clave = 'DB_Version';